// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type SysTenant struct {
	ID             int32          `json:"id"`
	UniqueID       uuid.NullUUID  `json:"unique_id"`
	HandleID       string         `json:"handle_id"`
	Code           sql.NullString `json:"code"`
	Name           sql.NullString `json:"name"`
	Description    sql.NullString `json:"description"`
	SessionTimeout sql.NullInt32  `json:"session_timeout"`
	CreatedDate    sql.NullTime   `json:"created_date"`
	CreatedBy      sql.NullInt32  `json:"created_by"`
	CreatedByName  sql.NullString `json:"created_by_name"`
	UpdatedDate    sql.NullTime   `json:"updated_date"`
	UpdatedBy      sql.NullInt32  `json:"updated_by"`
	UpdatedByName  sql.NullString `json:"updated_by_name"`
}

type User struct {
	ID             int32          `json:"id"`
	SysTenantID    int32          `json:"sys_tenant_id"`
	UniqueID       uuid.NullUUID  `json:"unique_id"`
	HandleID       sql.NullString `json:"handle_id"`
	FirstName      sql.NullString `json:"first_name"`
	LastName       sql.NullString `json:"last_name"`
	IsActive       sql.NullBool   `json:"is_active"`
	Email          sql.NullString `json:"email"`
	Phone          sql.NullString `json:"phone"`
	Password       sql.NullString `json:"password"`
	Roles          []string       `json:"roles"`
	LastAccessedAt sql.NullTime   `json:"last_accessed_at"`
	CreatedDate    sql.NullTime   `json:"created_date"`
	CreatedBy      sql.NullInt32  `json:"created_by"`
	CreatedByName  sql.NullString `json:"created_by_name"`
	UpdatedDate    sql.NullTime   `json:"updated_date"`
	UpdatedBy      sql.NullInt32  `json:"updated_by"`
	UpdatedByName  sql.NullString `json:"updated_by_name"`
}
