// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"context"
)

type Querier interface {
	AddSysTenant(ctx context.Context, arg AddSysTenantParams) (SysTenant, error)
	AddUser(ctx context.Context, arg AddUserParams) (User, error)
	DeleteUser(ctx context.Context, arg DeleteUserParams) error
	GetUser(ctx context.Context, arg GetUserParams) (User, error)
	GetUsers(ctx context.Context, arg GetUsersParams) ([]User, error)
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
}

var _ Querier = (*Queries)(nil)
